### PR TITLE
allow_url_fopen

### PR DESCRIPTION
**Pull request by frostmakk**
Added php.ini setting allow_url_fopen, and removed the "SITE" heading from plugins, as suggested by @sozzled some time ago.

### CODE REVIEW

**Comment by sozzled** [comment]
See comment posted on the J! forum:  https://forum.joomla.org/viewtopic.php?f=804&t=972434

**Comment by frostmakk** [comment]
Removed "Site" from libraries.

**Comment by sozzled** [comment]
Looks good to me, thanks.  See test at https://forum.joomla.org/viewtopic.php?f=804&t=972434&p=3571681#p3571680

Are you going to modify the Version number and date modified in the source?

**Comment by frostmakk** [comment]
@mandville usually take care of that after she has cooked up a weird release name.

**Comment by sozzled** [comment]
OK. (heh-heh-heh).  Good to go as far as I'm concerned.

**Comment by mandville** [comment]
1.4.9 lambrusca  released

**Pull request merged**
