### PR TITLE
Multilanguage

### PR DESCRIPTION
**Pull request by elkuku**
Hello,
I was recently playing with a script that creates a single, multi language capable, file from a set of PHP files. So I thought that FPA would be a good candidate to test this thing..

**How does it work ?**
It basically scans your PHP code for translatable strings, creates or updates language files, and then builds everything into a single file.

**Advantages:**
- By providing language files in a standard language file format, things should become a bit easier for fellow translators.
- By splitting up the PHP code into several files it should become more maintainable.

You may have a look at the actual (releasable) "**result**" after running the script: https://github.com/downloads/elkuku/FPA/fpa.php.tar.gz

This is actually a "work in progress", so it is not meant to be merged "as is"...

I just wanted to know what you think about _the idea_ and if it makes sense to invest more time in "refactoring" FPA ?

### CODE REVIEW

**Comment by PhilD13** [comment]
At first look I think this is a really good idea, I like it and it deserves further work.

**Comment by PhilD13** [comment]
Perhaps there is some way to have a separate option (just below the Run-Time Options when the show FPA option is open) for generating the post in English. This way, we would get the best of both worlds. Non English speaking persons can view the FPA script and results in their language and if desired can they can post the results to a forum (security forum for example) in English or their language to a different forum if that is what is desired. What do you think of this idea?

**Comment by elkuku** [comment]
Thanks for your comments, very encouraging ;)
As for your suggestion: If I get you right you mean to have the contents of the "page" in e.g. finnish, while the post "output" should be in english ? (those tiny red on yellow letters inside the `<textarea>` that you are meant to post to the forum) 

huh - I believe that's not possible, because it would require to load two different languages without overwriting... not even J! is able to do so ;)
On the other hand you can just switch the languages while your settings (runtime options, information privacy... will remain).
Is that an option ?

I did some structural changes and finally changed all language "defines" to their proper function call - I hope you will accept it, or i will shoot myself :P

I also added a Finnish language file including your existing translations. Are there other translations available ?
If you get scared when opening the po language files -- please don't ;) They are not meant to be edited "by hand" - but you can do so of course..
A much better solution would be to create a project on https://www.transifex.net - a lot of J devs do so nowerdays - and let the https://opentranslators.transifex.net do the rest.
If you need help on this - please ask ;)

**Comment by PhilD13** [comment]
"As for your suggestion: If I get you right you mean to have the contents of the "page" in e.g. finnish, while the post "output" should be in english ? (those tiny red on yellow letters inside the <textarea> that you are meant to post to the forum) " 

Yep that was what I was basically talking about. 

"On the other hand you can just switch the languages while your settings (runtime options, information privacy... will remain). Is that an option ?" 

That would work and serve the purpose.

I did some structural changes and finally changed all language "defines" to their proper function call - I hope you will accept it, or i will shoot myself :P

I don't at this time have any issue, but I would like to wait a short time. Being somewhat pressed for time for reviewing and to just to be clear, with the modifications etc., there will be a single (fpa.php) script to install or will there be an additional language file(s)?  In other words what is the end user going to need to install?

"I also added a Finnish language file including your existing translations. Are there other translations available ?"

No Russ just set up the structure of the GITHub that way for future. I did send an email to Tero Kankaanperä as he did the Finnish translation asking if he had any input and to post here (or contact me) if he did.

"A much better solution would be to create a project on https://www.transifex.net - a lot of J devs do so nowerdays - and let the https://opentranslators.transifex.net do the rest.
If you need help on this - please ask ;)"

Can you make this happen or set it up?

**Comment by PhilD13** [comment]
I'll see about a merge sometime late this afternoon or early evening unless someone wants me to hold off.

**Comment by elkuku** [comment]
Oh that's OK - take your time. I understand that this are quite _substantial_ changes to the project. Maybe waiting for Russ's opinion ?

To clarify: The "final product" - the **release** - will remain a single file, `fpa.php`, all available languages included ;)

To start the project on transifex it would be necessary to merge first, as transifex tracks the "original" (english) language file for changes - pretty neat ;)

**Comment by PhilD13** [comment]
I sent off an email to Russ for his opinion, hopefully I will hear back 
soon.

**Comment by PhilD13** [comment]
Merged the commit request and created a new branch called multilanguage This is the branch that transiflex translators should use. I did this as I would like to keep the fpa-en branch clean of extra files as we are currently using the fpa-en branch file and docs in the Joomla security forums as a direct link (tar or zip) download of the auto generated packages for the branch. If this won't work for some reason let me know and we can discuss alternatives.

**Comment by elkuku** [comment]
I believe that makes perfect sense.
It also works for transifex - no problem at all. The project has been created at:
https://www.transifex.net/projects/p/fpa/

**Pull request merged**
