### PR TITLE
Multilanguage

### PR DESCRIPTION
**Pull request by elkuku**
Some language updates.
I also modified the readme to include the standard readme as well as a nice transifex stats image.

The project has been created at:
https://www.transifex.net/projects/p/fpa/
If you want to be added as maintainers, please let me know your transifex username.

Let's see what happens :)

### CODE REVIEW

**Comment by mandville** [comment]
can i be clear, is the project replicated at transifex or just the language side of it?

**Comment by elkuku** [comment]
It's just the language file ;)

**Comment by PhilD13** [comment]
I have a user account on transifex. Username is:  PhilD
You can add me as a maintainer.

I'm also going to merge this pull so everything is up to date.

Just the template.pot file is on transifex

**Comment by elkuku** [comment]
You have been added ;)

**Comment by mandville** [comment]
not that i really want one but you may aswell add mandville to that site

and the original email didnt make it clear

C Mandville
Joomla Community Connect Administrator
JSST Member

On Sun, Nov 6, 2011 at 12:06 AM, Nikolai Plath
reply@reply.github.com
wrote:

**Comment by elkuku** [comment]
Hello mandville,
you have just been added as a maintainer to the transifex site.

Any further questions, please feel free to ask ;),
Nikolai

**Comment by mandville** [comment]
Any further questions, please feel free to ask ;),.......

Why is my bus late.

On Sunday, November 6, 2011, Nikolai Plath <
reply@reply.github.com>
wrote:

> Hello mandville,
> your have just been added as a maintainer to the transifex site.
> 
> Any further questions, please feel free to ask ;),
> Nikolai
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ForumPostAssistant/FPA/pull/9#issuecomment-2645955

## 

C Mandville
Joomla Community Connect Administrator
JSST Member

**Comment by elkuku** [comment]
Because they always are ;)

**Comment by PhilD13** [comment]
I see there is some activity on transifex,

What about the following strings? Should they be added to the translations file?

define ( '_RES', 'Bug Report Assistant' );
define ( '_RES', 'Forum Post Assistant' );
define ( '_FPA_NONE', 'None' );//@todo: constant ?
define ( '_FPA_M', 'Maybe' );//@todo: constant ?
define ( '_FPA_U', 'Unknown' );//@todo: constant ?
define ( '_FPA_3PD', '3rd Party' );//@todo: constant ?
define ( '_FPA_DNE', 'Does Not Exist' );//@todo: constant ?
define ( '_FPA_NA', 'N/A' );//@todo: constant ?
define ( '_RES_RELEASE', 'Beta' );         // can be Alpha, Beta, RC, Final
define ( '_RES_BRANCH', 'playGround' );    // can be playGround (Alpha/Beta only), currentDevelopment (RC only), masterPublic (Final only)
define ( '_FPA_VER', 'Version' );
define ( '_RES_FPALATEST', 'Get the latest release of the ' );

Also the other day when I looked at the current fpa-en version code I noticed there are quite a few words that are not in defines statements that probably should be otherwise certain sections of the script will be mixed (english and other) language. I was thinking about adding them, but did not get around to it at that time. If I were to go ahead and do this at some point how should this be handled? Would I just run the language script on it when done?

**Comment by elkuku** [comment]
Yes I also noticed that there are still a lot of hard coded strings.
The procedure would be this:
1) Add the function calls to the PHP code
Example:

``` php
<?php
echo 'Hello world';
// Change to :
echo qText('Hello world');
```

2) When you are finished, execute the `languagebuilder.php` script.
This should update the pot template and the po language files.
Please verify the result, as the script may still have some glitches ;)
Commit (and `git push`) the `template.pot` file to GitHub. It should be tracked by Transifex and made available for translation.

As for the remaining defines and their @todos: I believe it would be good to change them to function calls wherever they are used in output.
Example:

```
// This may be changed to: echo qText('Something appropiate...');
echo _FPA_NA;

// This should stay:
$fpa['supportENV']['badPHP'][0]     = _FPA_NA;
```

In one of the next steps we can change the remaining defines to proper integers - when one of us gets time...

The version number and info might go to the config.xml - @todo

`_RES` requires a different solution - will think about it..

Russ ?

Transifex:
Glad that it seems to work also for this project ;) I am sure if it gets a bit more "official" it would get even more attention.

Also the fact that it becomes multilingual will improve the acceptance by the community. Speaking of which, I think it strongly needs a (default) mode that shows only information for the "average" user. The ammount of information shown ATM is quite intimidating ;)

Back to Transifex. If you wonder how to get the translated language files back to your "hard drive".. It took me a while to figure it out, but Transifex provides a neat little client script that does exactly this job. Installation is as easy as a
`(sudo) easy_install --upgrade transifex-client`
and it reads the file provided in .tx/config file which I already included in "our" project.

So all you have to do is a simple `tx pull` to get all your language files. Nice ?

@todo: A big todo, which I would consider an importantant step in refactoring, is stripping out all the inline CSS declarations, change them to classes, and move them to the already existing CSS file.
Anyone who likes CSS stuff ?

Sorry for the long "post", regards,
Nikolai

**Comment by PhilD13** [comment]
Hmm, I;m not really much of a programmer but I took a look and maybe as 
you have time you should make the edits to the hard coded stuff. I think 
I understand the basics but would probably be very slow at it or prone 
to making mistakes that may break the code.

For example I take a line like this:
echo '<div class="normal-note"><span class="warn-text">'. _FPA_U 
.'</span></div>';
$snapshot['phpSUP4J'] = _FPA_U;

and change it to:
echo '<div class="normal-note"><span class="warn-text">'. 
qText('Unknown') .'</span></div>';
$snapshot['phpSUP4J'] = qText('Unknown');

but something like this should stay?
if ( $fpa['supportENV']['minPHP'] == _FPA_NA ) {

or should it be changed to
if ( $fpa['supportENV']['minPHP'] == qText('N/A') ) {

**Comment by elkuku** [comment]
Um.. I am afraid I lost your reply - sry _blush_
I believe the removal of the remaining defines require some careful thinking ;)

Also: Would it be possible to get somebody to test what has already be done -- just to ensure that nothing got broken along the way ? This would be great.

**Pull request merged**
