### PR TITLE
Table counts

### PR DESCRIPTION
**Pull request by frostmakk**
Split table counts into tables with prefix from config, and other tables.
Removed output sections that were never shown. (Always restricted.)
Added a not supported by FPA message when Microsoft SQL Server is detected.
Some minor housekeeping.

For testing please use fpa-en.php in the FPA-FM branch.

### CODE REVIEW

**Comment by Webdongle** [comment]
Please a link to the FPA-FM branch

**Comment by frostmakk** [comment]
shot

**Comment by Webdongle** [comment]
Thanks ... had trouble finding that again.  Ran a test https://forum.joomla.org/viewtopic.php?f=804&t=979231
It took longer than normal to run it but looks ok.

I vote **PASS** 

Addendum
Is it normal for all 4 to show yes PHP CGI: Yes | Server SU: Yes | PHP SU: Yes | Custom SU (LiteSpeed/Cloud/Grid): Yes

**Comment by frostmakk** [comment]
That part is an experimental feature put into the script long before I started working with the FPA.
I have no idea if, or how it is supposed to work. I have my doubts about how accurate it is. 
Edit:
There is an old issue regarding this. #17

**Comment by Webdongle** [comment]
Need one more test please

**Comment by sozzled** [comment]
Please also change lines 36 and 39; then I'll download the test FPA and run the test on the J! forum.  Thanks.

**Comment by Webdongle** [comment]
Why do you want them changed?

**Comment by sozzled** [comment]
I think, that when I download the file (with the changed version number) and use the test version of the FPA (with a different version number to v1.4.9 which is the current version) and post the output on the forum, then it will be clear that I am using a different version to the "production" version.  Does that make sense?

**Comment by Webdongle** [comment]
It is illogical to change the version number on the pr because it is not a new version.  If you post to https://forum.joomla.org/viewtopic.php?f=804&t=979231 it will be clear that it is a test of the Test of FPA-FM branch

If you used git and Merged the pr to your branch then the version number would not change.  Therefore changing the version number would be inconsitant.

**Comment by frostmakk** [comment]
Happy now sozzled?

**Comment by sozzled** [comment]
@frostmakk I'm working on it.  I rebuilt my PC and I need to update my settings in FileZilla.  Sorry for the time that I'm taking.

@Webdongle:  it is logical that a PR relates to a new version and, when testing a PR, all the changes in merging the PR with the master source are included.  A PR may not be a new **production** version but it's a new version that's being prepared for release.  When I develop new versions for testing, I always change the version number details.  It just makes things easier.

**Comment by sozzled** [comment]
Posted my test on the forum.  If you want to release this with "weird release name", that's OK with me.  I can't see anything wrong with the test.  Can you?

**Comment by mandville** [comment]
can you double check i didn't mess that up when i named the release

**Comment by sozzled** [comment]
It seems OK, @mandville.  Have a look at the latest post I made on the forum.  Does this look OK to all of you?  I can't see anything obviously wrong with this.

**Comment by sozzled** [comment]
I think, in future, I think we should always change the version number in a PR before other people test things so that we're clear that the PR relates to something different to the current production version.  It also means that, when the PR is merged and becomes the new production version, we haven't missed this step in the process.  It **_also_** means that, when people post the FPA on the forum (and they're using something with an old version number) we can be more certain that they're using the latest production release.  It's just easier all around if we do this at the beginning rather than at the end.

**Comment by Webdongle** [comment]
Was it a new feature then new release version I suppose?

Oh and is it still @release Beta

Other than that it looks good 👍

**Comment by sozzled** [comment]
Even a one-line change is a new version.  Has nothing to do with "new features".

**Comment by frostmakk** [comment]
This PR is FUBAR M.
Closing and starting over.

**Comment by sozzled** [comment]
OK.  BTW, I posted another test FPA message on the forum (a more complex website).

**Pull request closed without merging**
