### PR TITLE
More, and then some

### PR DESCRIPTION
**Pull request by frostmakk**
Well, it's that time of year again.
The snow is knee deep and I have retreated to my computer cave.

This PR is mostly about GUI changes:

* FPA issue #122
Added note regarding Logs folders.
Added API/ folder to core folder permissions checks from vJ4.

CFPC

* Added 'fileinfo'(from vJ4), and 'gd', as required PHP extensions.

* Changed the order of searching for the platform file to find the most recent. There have been cases where old leftover platform files have given false results like this:

nooku

* Changed the definition of $phpenv['phpCGI']
Before this PR only phpAPI CGI or CGI-FAST counted as 'phpCGI'. I have included litespeed, fpm-fcgi and uwsgi.
Feel free to protest @RussW   😄 

SUC

* Added check for minimum MariaDB version.

* Redacted the rest of the 'sensitive' information from the GUI when Privacy is enabled.

* Added check for disabled update sites.

* MariaDB returns one dbHOSTSTAT less than MySQL, so had to IF the last explode to get rid of errors.

* Added a new section at the bottom of the GUI. 'Additional Findings & Notes' as a kind of crossover from Fishikawa.
This is the place to elaborate over issues cryptically reported in the FPA, or to describe issues that dont fit in elsewhere.
Currently issues reported in this section are:
Disabled update sites.
Wrong Session_handler 'none' on J4+.
Elaboration on the multiple version files found issue.
No tables in database.
No tables in database with config prefix, but others exist. 
Note regarding J3 on PHP 8.1+
Note regarding J4 on PHP 8.2+ TODO: Update when J4 is patched.
Notes regarding minimum MariaDB version and J4.

AFandN

This one will only show if you are running J3.10 and a MariaDB version below 10.1
MinMariaOnJ310

As always: Please test.
Comments and suggestions are welcome.

### CODE REVIEW

**Comment by mandville** [comment]
Sounds amazing
 Where is the option to tell a ise4 5h3u are not worthy of running joomla

**Comment by RussW** [comment]
No complaints from me with the updates, as ever thank you for your time and diligence. 

If we are adding all the current SAPI interfaces, do we also want to add 'phpdbg' and even the rarely used 'fuzzer' interfaces too?

I'll test it out over the coming weekend.

**Comment by frostmakk** [comment]
Please do. That's your domain. I'm totally lost when it comes to server setups.

@mandville  Mr. Nice Guy probably wouldn't have approved that option. 🤣

**Review by RussW — APPROVED** [review]
All fine with me, everything appears to work as described, well done.

_Having reviewed the PHP SAPI interfaces, I see no reason to add my previously proposed interface types (phpdbg, cli-server & fuzzer). If a user has phpdbg enabled they either have bigger problems or are developing PHP itself, cli-server is related to older versions of the Nginx server which now only runs in CGI mode and fuzzer is very rarely used or needed and wouldn't provide any useful for this use case._

**Comment by frostmakk** [comment]
I noticed that some servers reported a fake MariaDB version like this:  5.5.5-10.4.25-MariaDB-cll-lve-log
This was messing with the compatibility checs, so I added a routine to strip off those 6 first characters.
Any comments @RussW ?

**Comment by RussW** [comment]
The additional information displayed with MariaDB is only under certain circumstances such as when running under LVE Control with MySQL Governor (such as the default for CloudLinux Enterprise) it displays the LVE container manager version as a prefix to the MariaDB version, so it is fine to be stripped/removed from the output for clarity.

Well caught @frostmakk

**Comment by frostmakk** [comment]
Thanks for the insight. So it's a version number. That could be a problem. I hope there aren't too many out there. Will keep an eye on this, and re-think the filter if necessary.

**Comment by frostmakk** [comment]
v1.6.6 released.

**Pull request merged**
