### PR TITLE
BBCode issues

### PR DESCRIPTION
**Pull request by frostmakk**
Fixed a bug that slightly messed up the BBCode when show plugins was deselected.
Changed color for 3rdParty extensions for better readability.
Removed some BBCode tags to reduce the post size.

### CODE REVIEW

**Comment by mandville** [comment]
not sure the dull orange colour works. ` thanks so far

[](https://postimg.org/image/f0hnxncip/)

**Comment by frostmakk** [comment]
Agree. That's why i changed the colour in this PR.
Looks like this now:
screen

I'm working on another improvement. Will be ready in a couple of hours.

**Comment by frostmakk** [comment]
One last commit added to the PR. 
Changes are:
Fixed one more PHP7.1 error.
Changed "Owner" and "Group" to protected information in the post output. Many users masked this anyway.
Added a feature to count the number of characters in the post output.

image

**Comment by frostmakk** [comment]
M.
The PR #27 is ready to be merged, if You approve.

**Comment by mandville** [comment]
under test

**Review by PhilD13 — APPROVED** [review]
Looks ok to me. Recommend doing a commit and then I will add the edits for MariaDB check. Sound good?

**Comment by frostmakk** [comment]
Nice. 👍

**Comment by mandville** [comment]
can you explain the ""1""  after the extensions

**Comment by frostmakk** [comment]
It show if the extension is enabled (1) or not (0)

**Pull request merged**
